### ISSUE TITLE
Bug report — the text is bugged (probably caused by text color i think)

### ISSUE THREAD

**Issue by AntogamerYT** [fasmga/frontend#10]
## Description
> Briefly describe your issue here

You can't see the text on the fasmga site

---
## Steps to reproduce
1. Go to the fasm.ga site
2. Try to read the text (the one below the "Input any URL")
> You can add more. Please leave the '1's in the list items as they are, as they are automatically numbered

<details><summary><b>Screenshots</b></summary>

![image](https://user-images.githubusercontent.com/64664639/151670038-c77bc93a-7698-432c-8d97-0836f922c69a.png)

</details>

---
## Expected behavior
> A clear and concise description of what you expected to happen.

The text should be readable

---
## Platform info
| Windows 10 | Edge 97.0.1072.76 | Desktop |
---
<details><summary><b>Additional context</b></summary>

> Do you have anything else to add? Put it here!

No.
</details>

**Comment by StuckDuck7710** [comment]
Thanks for reporting, fixed

| Dark | Light |
| ---- | ----- |
| ![image](https://user-images.githubusercontent.com/71439748/151670321-354c54ba-329f-48e0-87ce-02b8ffbb55bc.png) | ![image](https://user-images.githubusercontent.com/71439748/151670391-7b36e6db-1572-40d3-aa0d-6a614e2049c2.png) |
