### ISSUE TITLE
Frontend report

### ISSUE THREAD

**Issue by Asfaltinho** [fasmga/frontend#12]
## Description
> 1) On the phone, in the settings, there is no text of the options making them not very intuitive
> 2) The examples boxes and the welcome box aren't centered in the home page

---
## Steps to reproduce
![Screenshot_2022-01-30-14-55-47-261_com brave browser](https://user-images.githubusercontent.com/83889522/151703010-35c5b2be-0f8a-4176-8b2c-d123893f8045.jpg)
![Screenshot_2022-01-30-14-55-43-091_com brave browser](https://user-images.githubusercontent.com/83889522/151703013-363b4cc7-19e7-4829-be6d-bd256ec66ae4.jpg)

1) 1. Just go on the site
2) 1. Go on the site
    2. click settings
---
## Expected behavior
> A clear and concise description of what you expected to happen.
Prolly they aren't centered and there is no text GRAZIE AL CAZZK.
---
## Platform info
| Android 11 - MIUI 12.5.7 EEA | Brave Browser based on Chromium 97 | POCO F3 |

**Comment by StuckDuck7710** [comment]
1. Intended, navbar item titles are hidden on mobile to save space, but we could eventually change that if the current behavior isn't intuitive
2. I'll be working on this

Thank you for reporting!

**Comment by Asfaltinho** [comment]
yw :D

**Comment by StuckDuck7710** [comment]
Fixed the misaligned info boxes.

Additional options to customize user experience, like forcing navbar text on mobile UI, are currently planned for upcoming releases.

Thanks for contributing
